name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 17
        uses: actions/setup-java@v2.4.0
        with:
          java-version: 17.0.1
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build